# Default Documentation Theme
name: default
description: Default documentation theme with clean, modern design
author: Supabase
version: 1.0.0
created: '2025-05-24T00:00:00.000Z'
updated: '2025-05-24T00:00:00.000Z'

# Theme Variables
variables:
  # Colors
  color-primary: '#3ECF8E'
  color-secondary: '#6EE7B7'
  color-text: '#1F2937'
  color-text-light: '#6B7280'
  color-background: '#FFFFFF'
  color-border: '#E5E7EB'
  color-code-bg: '#F3F4F6'
  
  # Typography
  font-sans: "'Inter', system-ui, -apple-system, sans-serif"
  font-mono: "ui-monospace, SFMono-Regular, Menlo, monospace"
  font-size-base: '16px'
  font-size-sm: '0.875rem'
  font-size-lg: '1.125rem'
  line-height-base: '1.6'
  line-height-heading: '1.3'
  
  # Spacing
  spacing-base: '1rem'
  spacing-sm: '0.5rem'
  spacing-md: '1.5rem'
  spacing-lg: '2rem'
  spacing-xl: '4rem'
  
  # Layout
  max-width: '65rem'
  sidebar-width: '18rem'
  header-height: '4rem'
  border-radius: '0.25rem'

# Templates
templates:
  html: |
    <!DOCTYPE html>
    <html lang="en">
      <!-- HTML template content -->
    </html>
  
  pdf: |
    ---
    title: {{title}}
    author: {{author}}
    date: {{date}}
    ---
    
    {{{content}}}
  
  epub: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <package xmlns="http://www.idpf.org/2007/opf">
      <!-- EPUB template content -->
    </package>
  
  docx: |
    {
      "sections": [
        {
          "properties": {},
          "children": []
        }
      ]
    }

# Styles
styles:
  # Layout styles
  layout: |
    .layout {
      display: grid;
      grid-template-columns: var(--sidebar-width) 1fr;
      min-height: 100vh;
    }

    .header {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      height: var(--header-height);
      padding: 0 var(--spacing-base);
      background: var(--color-background);
      border-bottom: 1px solid var(--color-border);
      display: flex;
      align-items: center;
      justify-content: space-between;
      z-index: 10;
    }

    .sidebar {
      position: fixed;
      top: var(--header-height);
      left: 0;
      bottom: 0;
      width: var(--sidebar-width);
      padding: var(--spacing-base);
      border-right: 1px solid var(--color-border);
      overflow-y: auto;
    }

    .main {
      margin-left: var(--sidebar-width);
      margin-top: var(--header-height);
      padding: var(--spacing-lg);
      max-width: var(--max-width);
    }

  # Typography styles
  typography: |
    body {
      font-family: var(--font-sans);
      font-size: var(--font-size-base);
      line-height: var(--line-height-base);
      color: var(--color-text);
    }

    h1, h2, h3, h4, h5, h6 {
      margin: 2em 0 1em;
      font-weight: 600;
      line-height: var(--line-height-heading);
    }

    h1 { font-size: 2.5rem; }
    h2 { font-size: 2rem; }
    h3 { font-size: 1.5rem; }
    h4 { font-size: 1.25rem; }
    h5 { font-size: 1rem; }
    h6 { font-size: 0.875rem; }

    p {
      margin: 1em 0;
    }

    a {
      color: var(--color-primary);
      text-decoration: none;
    }

    code {
      font-family: var(--font-mono);
      font-size: 0.9em;
    }

  # Color styles
  colors: |
    :root {
      --color-primary: {{variables.color-primary}};
      --color-secondary: {{variables.color-secondary}};
      --color-text: {{variables.color-text}};
      --color-text-light: {{variables.color-text-light}};
      --color-background: {{variables.color-background}};
      --color-border: {{variables.color-border}};
      --color-code-bg: {{variables.color-code-bg}};
    }

  # Component styles
  components: |
    /* Code blocks */
    pre {
      margin: 1em 0;
      padding: var(--spacing-base);
      background: var(--color-code-bg);
      border-radius: var(--border-radius);
      overflow-x: auto;
    }

    /* Tables */
    table {
      width: 100%;
      margin: 1em 0;
      border-collapse: collapse;
    }

    th, td {
      padding: 0.75rem;
      border: 1px solid var(--color-border);
      text-align: left;
    }

    /* Blockquotes */
    blockquote {
      margin: 1em 0;
      padding: 1em;
      border-left: 4px solid var(--color-primary);
      background: var(--color-code-bg);
    }

    /* Lists */
    ul, ol {
      margin: 1em 0;
      padding-left: 1.5em;
    }

    /* Images */
    img {
      max-width: 100%;
      height: auto;
      border-radius: var(--border-radius);
    }

# Print styles
print: |
  @media print {
    .header, .sidebar {
      display: none;
    }

    .main {
      margin: 0;
      max-width: none;
    }

    a[href]::after {
      content: " (" attr(href) ")";
    }
  }

# Mobile styles
mobile: |
  @media (max-width: 768px) {
    .layout {
      grid-template-columns: 1fr;
    }

    .sidebar {
      display: none;
    }

    .main {
      margin-left: 0;
    }
  }