name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/stripe-webhook/**'
  pull_request:
    branches: [main]
    paths:
      - 'supabase/functions/stripe-webhook/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/import_map.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Check Format
        run: |
          cd supabase/functions/stripe-webhook
          deno fmt --check

      - name: Lint
        run: |
          cd supabase/functions/stripe-webhook
          deno lint

      - name: Type Check
        run: |
          cd supabase/functions/stripe-webhook
          deno check **/*.ts

      - name: Run Tests
        run: |
          cd supabase/functions/stripe-webhook
          deno test --allow-net --allow-env --allow-read
        env:
          DEBUG: false
          STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}
          WEBHOOK_SECRET: ${{ secrets.TEST_WEBHOOK_SECRET }}

      - name: Upload Coverage
        if: success()
        run: |
          cd supabase/functions/stripe-webhook
          deno test --coverage=coverage --allow-net --allow-env --allow-read
          deno coverage ./coverage --lcov > coverage.lcov

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./supabase/functions/stripe-webhook/coverage.lcov
          flags: unittests
          fail_ci_if_error: false